[workspace]
resolver = "2"
members = ["generator", "glowing_dots", "glowing_dots_macros", "glowing_dots_renderer"]

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 1
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 1
overflow-checks = false
